name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://priyaramky:$HF_TOKEN@huggingface.co/spaces/priyaramky/nutriassistai main
